export const levels = {
  50: {
    name: 'Superman',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694084/commit_everyday_assets/superman_rdpvr2.png',
  },
  49: {
    name: 'Goku',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694076/commit_everyday_assets/goku_lbyqmy.png',
  },
  48: {
    name: 'Thor',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694084/commit_everyday_assets/thor_f9qph2.png',
  },
  47: {
    name: 'Naruto',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/naruto_uvarv7.png',
  },
  46: {
    name: 'Wonder Woman',
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694085/commit_everyday_assets/wonder_woman_cgn9yz.png',
  },
  45: {
    name: 'Iron Man',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694077/commit_everyday_assets/iron_man_sms4o2.png',
  },
  44: {
    name: 'Batman',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/batman_s79wx5.png',
  },
  42: {
    name: 'Gandalf',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694076/commit_everyday_assets/gandalf_hoqcva.png',
  },
  43: {
    name: 'Spider-Man',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694083/commit_everyday_assets/spider_man_l5hdb4.png',
  },
  41: {
    name: 'Wolverine',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694084/commit_everyday_assets/wolverine_ccnnhd.png',
  },
  40: {
    name: 'Link',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694079/commit_everyday_assets/link_l6rnaj.png',
  },
  39: {
    name: 'Yoshi',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694086/commit_everyday_assets/yoshi_rdchhu.png',
  },
  38: {
    name: 'Master Chief',
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694079/commit_everyday_assets/master_chief_u7bven.png',
  },
  37: {
    name: 'Kratos',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694078/commit_everyday_assets/kratos_c61qqu.png',
  },
  36: {
    name: 'Sonic',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694082/commit_everyday_assets/sonic_hbxuu3.png',
  },
  35: {
    name: 'Mega Man',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/megaman_mfj68i.png',
  },
  34: {
    name: 'Pikachu',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/pikachu_kmz3pu.png',
  },
  33: {
    name: 'Lara Croft',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694078/commit_everyday_assets/lara_croft_n3egre.png',
  },
  32: {
    name: 'Captain America',
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/captain_america_m8k3lr.png',
  },
  31: {
    name: 'Bulbusaur',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/bulbusaur_d9445u.png',
  },
  30: {
    name: 'Charizard',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/charizard_srtut3.png',
  },
  29: {
    name: 'Buckethead Zombie',
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694792/commit_everyday_assets/cheep_cheep_hxnhxu.png',
  },
  28: {
    name: 'Luigi',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694079/commit_everyday_assets/luigi_lvpxbf.png',
  },
  27: {
    name: 'Peach',
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/princess_peach_zmfaz1.png',
  },
  26: {
    name: 'Bowser',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/bowser_mg5ba2.png',
  },
  25: {
    name: 'Cheep Cheep',
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694792/commit_everyday_assets/cheep_cheep_hxnhxu.png',
  },
  24: {
    name: 'Kirby',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694077/commit_everyday_assets/kirby_bz0pb4.png',
  },
  23: {
    name: 'Crash Bandicoot',
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/crash_bandicoot_r5oa4m.png',
  },
  22: {
    name: 'Dhalism',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/dhalism_zwoywf.png',
  },
  21: {
    name: 'Toad',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694084/commit_everyday_assets/toad_sctzks.png',
  },
  20: {
    name: 'Ken',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694077/commit_everyday_assets/ken_iivc6u.png',
  },
  19: {
    name: 'Diddy Kong',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694076/commit_everyday_assets/diddy_kong_itlndn.png',
  },
  18: {
    name: 'Princess Zelda',
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694081/commit_everyday_assets/princess_zelda_b2v14a.png',
  },
  17: {
    name: 'Bullet Bill',
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/bullet_bill_vblqii.png',
  },
  16: {
    name: 'Cloud Strife',
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/cloud_strife_oquw2g.png',
  },
  15: {
    name: 'Blanka',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694370/commit_everyday_assets/blanka_godyof.png',
  },
  14: {
    name: 'Goomba',
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/New_Project_p3lcxu.png',
  },
  13: {
    name: 'Guile',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694244/commit_everyday_assets/guile_oo22zd.png',
  },
  12: {
    name: 'Gordon Freeman',
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694076/commit_everyday_assets/gordon_freeman_awbqu9.png',
  },
  11: {
    name: 'Squirtle',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694083/commit_everyday_assets/squirtle_ywoha3.png',
  },
  10: {
    name: 'Scorpion',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694081/commit_everyday_assets/scorpion_bicvof.png',
  },
  9: {
    name: 'Sub-Zero',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694083/commit_everyday_assets/subzero_grsqdz.png',
  },
  8: {
    name: 'Yoshi Egg',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694085/commit_everyday_assets/yoshi_egg_vdpzao.png',
  },
  7: {
    name: 'Shy Guy',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706695052/commit_everyday_assets/shy_guy_1_sbmjej.png',
  },
  6: {
    name: 'Ryu',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694081/commit_everyday_assets/ryu_t29dkb.png',
  },
  5: {
    name: 'Kamek',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694076/commit_everyday_assets/kamek_lyavef.png',
  },
  4: {
    name: 'Koopa',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694078/commit_everyday_assets/koopa_wniua8.png',
  },
  3: {
    name: 'Megaman',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/megaman_mfj68i.png',
  },
  2: {
    name: 'Knuckles',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694078/commit_everyday_assets/knuckles_uu8knq.png',
  },
  1: {
    name: 'Blinky',
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/blinky_umvzbc.png',
  },
};

export const users = [
  {
    id: 8,
    premium: false,
    name: 'connorkuljis',
    total: 155,
    most_active_day: 'Wednesday',
    rank: 76,
    median: '5.00',
    missed_days: 0,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/pikachu_kmz3pu.png',
    streak: 31,
  },
  {
    id: 9,
    premium: false,
    name: 'scarletquasar',
    total: 298,
    most_active_day: 'Wednesday',
    rank: 74,
    median: '10.28',
    missed_days: 3,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/dhalism_zwoywf.png',
    streak: 21,
  },
  {
    id: 10,
    premium: false,
    name: 'likendev',
    total: 78,
    most_active_day: 'Monday',
    rank: 70,
    median: '2.52',
    missed_days: 0,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/charizard_srtut3.png',
    streak: 31,
  },
  {
    id: 11,
    premium: false,
    name: 'nicoschriever',
    total: 98,
    most_active_day: 'Tuesday',
    rank: 74,
    median: '3.16',
    missed_days: 0,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694370/commit_everyday_assets/blanka_godyof.png',
    streak: 31,
  },
  {
    id: 12,
    premium: false,
    name: 'jasonleow',
    total: 121,
    most_active_day: 'Wednesday',
    rank: 74,
    median: '3.78',
    missed_days: 0,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694076/commit_everyday_assets/kamek_lyavef.png',
    streak: 32,
  },
  {
    id: 13,
    premium: false,
    name: 'torvalds',
    total: 284,
    most_active_day: 'Monday',
    rank: 70,
    median: '11.36',
    missed_days: 6,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694085/commit_everyday_assets/yoshi_egg_vdpzao.png',
    streak: 15,
  },
  {
    id: 14,
    premium: false,
    name: 'poppacalypse',
    total: 52,
    most_active_day: 'Saturday',
    rank: 58,
    median: '2.36',
    missed_days: 9,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694081/commit_everyday_assets/princess_zelda_b2v14a.png',
    streak: 10,
  },
  {
    id: 15,
    premium: false,
    name: 'yyx990803',
    total: 137,
    most_active_day: 'Thursday',
    rank: 58,
    median: '7.61',
    missed_days: 14,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694076/commit_everyday_assets/gordon_freeman_awbqu9.png',
    streak: 6,
  },
  {
    id: 7,
    premium: true,
    name: 't31k',
    total: 107,
    most_active_day: 'Sunday',
    rank: 76,
    median: '3.57',
    missed_days: 2,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694244/commit_everyday_assets/guile_oo22zd.png',
    streak: 20,
  },
  {
    id: 16,
    premium: false,
    name: 'navinpeiris',
    total: 381,
    most_active_day: 'Tuesday',
    rank: 82,
    median: '11.91',
    missed_days: 0,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694370/commit_everyday_assets/blanka_godyof.png',
    streak: 32,
  },
  {
    id: 17,
    premium: false,
    name: 'shafakyildiz',
    total: 175,
    most_active_day: 'Tuesday',
    rank: 64,
    median: '6.03',
    missed_days: 2,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694078/commit_everyday_assets/koopa_wniua8.png',
    streak: 13,
  },
  {
    id: 18,
    premium: false,
    name: 'uthsobcb',
    total: 84,
    most_active_day: 'Friday',
    rank: 54,
    median: '4.00',
    missed_days: 11,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694079/commit_everyday_assets/master_chief_u7bven.png',
    streak: 5,
  },
  {
    id: 20,
    premium: false,
    name: 'bjoentrepreneur',
    total: 75,
    most_active_day: 'Sunday',
    rank: 68,
    median: '4.17',
    missed_days: 13,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694084/commit_everyday_assets/wolverine_ccnnhd.png',
    streak: 16,
  },
  {
    id: 21,
    premium: false,
    name: 'mcnaveen',
    total: 129,
    most_active_day: 'Sunday',
    rank: 86,
    median: '4.03',
    missed_days: 0,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694792/commit_everyday_assets/cheep_cheep_hxnhxu.png',
    streak: 32,
  },
  {
    id: 22,
    premium: false,
    name: 'mxsjoberg',
    total: 995,
    most_active_day: 'Friday',
    rank: 90,
    median: '31.09',
    missed_days: 0,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694078/commit_everyday_assets/koopa_wniua8.png',
    streak: 32,
  },
  {
    id: 23,
    premium: false,
    name: 'CyrusZei',
    total: 468,
    most_active_day: 'Monday',
    rank: 86,
    median: '14.63',
    missed_days: 0,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694081/commit_everyday_assets/scorpion_bicvof.png',
    streak: 32,
  },
  {
    id: 24,
    premium: false,
    name: 'shahriarAS',
    total: 128,
    most_active_day: 'Friday',
    rank: 64,
    median: '5.82',
    missed_days: 9,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694792/commit_everyday_assets/cheep_cheep_hxnhxu.png',
    streak: 16,
  },
  {
    id: 25,
    premium: false,
    name: 'anurag-Kochar-1',
    total: 192,
    most_active_day: 'Saturday',
    rank: 88,
    median: '6.19',
    missed_days: 0,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/naruto_uvarv7.png',
    streak: 31,
  },
  {
    id: 26,
    premium: false,
    name: 'ravana69',
    total: 1630,
    most_active_day: 'Friday',
    rank: 90,
    median: '50.94',
    missed_days: 0,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/bowser_mg5ba2.png',
    streak: 32,
  },
  {
    id: 27,
    premium: false,
    name: 'zignis',
    total: 252,
    most_active_day: 'Monday',
    rank: 78,
    median: '7.88',
    missed_days: 0,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/batman_s79wx5.png',
    streak: 32,
  },
  {
    id: 28,
    premium: false,
    name: 'prnk28',
    total: 108,
    most_active_day: 'Wednesday',
    rank: 56,
    median: '5.40',
    missed_days: 12,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/megaman_mfj68i.png',
    streak: 5,
  },
  {
    id: 29,
    premium: false,
    name: 'Temitope-Emmanuel',
    total: 1,
    most_active_day: 'Sunday',
    rank: 34,
    median: '1.00',
    missed_days: 30,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/bullet_bill_vblqii.png',
    streak: 1,
  },
  {
    id: 30,
    premium: false,
    name: 'timmywheels',
    total: 114,
    most_active_day: 'Friday',
    rank: 64,
    median: '3.93',
    missed_days: 3,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/bulbusaur_d9445u.png',
    streak: 15,
  },
  {
    id: 31,
    premium: false,
    name: 'pskd73',
    total: 232,
    most_active_day: 'Friday',
    rank: 72,
    median: '7.73',
    missed_days: 2,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/bowser_mg5ba2.png',
    streak: 21,
  },
  {
    id: 32,
    premium: false,
    name: 'drodol',
    total: 59,
    most_active_day: 'Thursday',
    rank: 52,
    median: '2.95',
    missed_days: 11,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694079/commit_everyday_assets/luigi_lvpxbf.png',
    streak: 13,
  },
  {
    id: 33,
    premium: false,
    name: 'deifos',
    total: 1,
    most_active_day: 'Sunday',
    rank: 34,
    median: '1.00',
    missed_days: 30,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694081/commit_everyday_assets/princess_zelda_b2v14a.png',
    streak: 1,
  },
  {
    id: 34,
    premium: false,
    name: 'oli799',
    total: 81,
    most_active_day: 'Thursday',
    rank: 52,
    median: '5.79',
    missed_days: 17,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/charizard_srtut3.png',
    streak: 3,
  },
  {
    id: 35,
    premium: false,
    name: 'andryore',
    total: 12,
    most_active_day: 'Saturday',
    rank: 40,
    median: '4.00',
    missed_days: 28,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694084/commit_everyday_assets/thor_f9qph2.png',
    streak: 1,
  },
  {
    id: 36,
    premium: false,
    name: 'Zyruks',
    total: 77,
    most_active_day: 'Saturday',
    rank: 66,
    median: '3.67',
    missed_days: 11,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694084/commit_everyday_assets/thor_f9qph2.png',
    streak: 13,
  },
  {
    id: 37,
    premium: false,
    name: 'Swsalim',
    total: 67,
    most_active_day: 'Tuesday',
    rank: 50,
    median: '3.19',
    missed_days: 10,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694081/commit_everyday_assets/princess_zelda_b2v14a.png',
    streak: 7,
  },
  {
    id: 38,
    premium: false,
    name: 'czue',
    total: 177,
    most_active_day: 'Wednesday',
    rank: 60,
    median: '10.41',
    missed_days: 15,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/princess_peach_zmfaz1.png',
    streak: 4,
  },
  {
    id: 39,
    premium: false,
    name: 'Bb',
    total: 0,
    most_active_day: null,
    rank: 1,
    median: null,
    missed_days: 31,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706695052/commit_everyday_assets/shy_guy_1_sbmjej.png',
    streak: 0,
  },
  {
    id: 40,
    premium: false,
    name: 'noudadrichem',
    total: 114,
    most_active_day: 'Wednesday',
    rank: 62,
    median: '4.56',
    missed_days: 7,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694086/commit_everyday_assets/yoshi_rdchhu.png',
    streak: 15,
  },
  {
    id: 41,
    premium: false,
    name: 'abishuablessmic',
    total: 119,
    most_active_day: 'Monday',
    rank: 70,
    median: '3.97',
    missed_days: 1,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694076/commit_everyday_assets/goku_lbyqmy.png',
    streak: 24,
  },
  {
    id: 42,
    premium: false,
    name: 'difra14',
    total: 38,
    most_active_day: 'Friday',
    rank: 38,
    median: '2.24',
    missed_days: 15,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/megaman_mfj68i.png',
    streak: 3,
  },
  {
    id: 43,
    premium: false,
    name: 'codeninja819',
    total: 75,
    most_active_day: 'Wednesday',
    rank: 52,
    median: '3.95',
    missed_days: 13,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/bowser_mg5ba2.png',
    streak: 8,
  },
  {
    id: 44,
    premium: false,
    name: 'TheoOliveira',
    total: 97,
    most_active_day: 'Wednesday',
    rank: 58,
    median: '4.04',
    missed_days: 8,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694084/commit_everyday_assets/superman_rdpvr2.png',
    streak: 10,
  },
  {
    id: 45,
    premium: false,
    name: 'nor0x',
    total: 173,
    most_active_day: 'Wednesday',
    rank: 62,
    median: '7.52',
    missed_days: 9,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694079/commit_everyday_assets/link_l6rnaj.png',
    streak: 9,
  },
  {
    id: 46,
    premium: false,
    name: 'nitverse',
    total: 69,
    most_active_day: 'Thursday',
    rank: 50,
    median: '5.75',
    missed_days: 20,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694083/commit_everyday_assets/subzero_grsqdz.png',
    streak: 8,
  },
  {
    id: 48,
    premium: false,
    name: 'go2sujeet',
    total: 43,
    most_active_day: 'Friday',
    rank: 44,
    median: '10.75',
    missed_days: 27,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694076/commit_everyday_assets/goku_lbyqmy.png',
    streak: 2,
  },
  {
    id: 49,
    premium: false,
    name: 'fauzaanu',
    total: 504,
    most_active_day: 'Saturday',
    rank: 96,
    median: '15.75',
    missed_days: 0,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694086/commit_everyday_assets/yoshi_rdchhu.png',
    streak: 32,
  },
  {
    id: 50,
    premium: false,
    name: '1codealot',
    total: 83,
    most_active_day: 'Friday',
    rank: 60,
    median: '3.61',
    missed_days: 8,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694084/commit_everyday_assets/toad_sctzks.png',
    streak: 14,
  },
  {
    id: 51,
    premium: false,
    name: 'ashishk1331',
    total: 54,
    most_active_day: 'Tuesday',
    rank: 48,
    median: '3.00',
    missed_days: 13,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694792/commit_everyday_assets/cheep_cheep_hxnhxu.png',
    streak: 9,
  },
  {
    id: 52,
    premium: false,
    name: 'wouterds',
    total: 753,
    most_active_day: 'Monday',
    rank: 78,
    median: '28.96',
    missed_days: 6,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/dhalism_zwoywf.png',
    streak: 14,
  },
  {
    id: 53,
    premium: false,
    name: 'walegg',
    total: 210,
    most_active_day: 'Wednesday',
    rank: 78,
    median: '6.56',
    missed_days: 0,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694370/commit_everyday_assets/blanka_godyof.png',
    streak: 32,
  },
  {
    id: 54,
    premium: false,
    name: '0xakash9',
    total: 89,
    most_active_day: 'Tuesday',
    rank: 56,
    median: '4.05',
    missed_days: 10,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/princess_peach_zmfaz1.png',
    streak: 7,
  },
  {
    id: 55,
    premium: false,
    name: 'idiglove',
    total: 17,
    most_active_day: 'Friday',
    rank: 30,
    median: '2.13',
    missed_days: 23,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/bulbusaur_d9445u.png',
    streak: 2,
  },
  {
    id: 56,
    premium: false,
    name: 'EthanPlant',
    total: 17,
    most_active_day: 'Thursday',
    rank: 30,
    median: '3.40',
    missed_days: 27,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/pikachu_kmz3pu.png',
    streak: 2,
  },
  {
    id: 57,
    premium: false,
    name: 'bbbbbrie',
    total: 12,
    most_active_day: 'Sunday',
    rank: 38,
    median: '2.40',
    missed_days: 26,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694084/commit_everyday_assets/wolverine_ccnnhd.png',
    streak: 2,
  },
  {
    id: 58,
    premium: false,
    name: 'cassidoo',
    total: 156,
    most_active_day: 'Wednesday',
    rank: 76,
    median: '5.03',
    missed_days: 0,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694078/commit_everyday_assets/lara_croft_n3egre.png',
    streak: 31,
  },
  {
    id: 59,
    premium: false,
    name: 'cdvillard',
    total: 55,
    most_active_day: 'Wednesday',
    rank: 44,
    median: '2.89',
    missed_days: 13,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/princess_peach_zmfaz1.png',
    streak: 3,
  },
  {
    id: 60,
    premium: false,
    name: 'jijojosein',
    total: 180,
    most_active_day: 'Thursday',
    rank: 64,
    median: '6.67',
    missed_days: 5,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/blinky_umvzbc.png',
    streak: 13,
  },
  {
    id: 61,
    premium: false,
    name: 'Spider',
    total: 0,
    most_active_day: null,
    rank: 10,
    median: null,
    missed_days: 0,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694084/commit_everyday_assets/superman_rdpvr2.png',
    streak: 0,
  },
  {
    id: 62,
    premium: true,
    name: 'kevinngth',
    total: 0,
    most_active_day: null,
    rank: 1,
    median: null,
    missed_days: 31,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/blinky_umvzbc.png',
    streak: 0,
  },
  {
    id: 63,
    premium: false,
    name: 'marcelc63',
    total: 171,
    most_active_day: 'Monday',
    rank: 58,
    median: '8.55',
    missed_days: 13,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694076/commit_everyday_assets/gordon_freeman_awbqu9.png',
    streak: 4,
  },
  {
    id: 64,
    premium: false,
    name: 'onerinas',
    total: 132,
    most_active_day: 'Monday',
    rank: 62,
    median: '5.08',
    missed_days: 6,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694083/commit_everyday_assets/spider_man_l5hdb4.png',
    streak: 11,
  },
  {
    id: 65,
    premium: false,
    name: 'chambrin',
    total: 65,
    most_active_day: 'Tuesday',
    rank: 46,
    median: '5.42',
    missed_days: 20,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/cloud_strife_oquw2g.png',
    streak: 4,
  },
  {
    id: 66,
    premium: false,
    name: 'erwamartin',
    total: 355,
    most_active_day: 'Thursday',
    rank: 70,
    median: '12.68',
    missed_days: 5,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706695052/commit_everyday_assets/shy_guy_1_sbmjej.png',
    streak: 11,
  },
  {
    id: 67,
    premium: false,
    name: 'mmaksi',
    total: 139,
    most_active_day: 'Sunday',
    rank: 84,
    median: '4.34',
    missed_days: 1,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/bowser_mg5ba2.png',
    streak: 30,
  },
  {
    id: 68,
    premium: false,
    name: 'rohanmahen',
    total: 229,
    most_active_day: 'Tuesday',
    rank: 76,
    median: '6.94',
    missed_days: 1,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694078/commit_everyday_assets/lara_croft_n3egre.png',
    streak: 30,
  },
  {
    id: 69,
    premium: false,
    name: 'boonsuen',
    total: 142,
    most_active_day: 'Friday',
    rank: 58,
    median: '5.92',
    missed_days: 8,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694078/commit_everyday_assets/knuckles_uu8knq.png',
    streak: 6,
  },
  {
    id: 70,
    premium: false,
    name: 'Oreoluwadnd',
    total: 0,
    most_active_day: null,
    rank: 1,
    median: null,
    missed_days: 31,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/charizard_srtut3.png',
    streak: 0,
  },
  {
    id: 71,
    premium: false,
    name: 'Alinxus',
    total: 16,
    most_active_day: 'Wednesday',
    rank: 30,
    median: '2.00',
    missed_days: 24,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/dhalism_zwoywf.png',
    streak: 2,
  },
  {
    id: 72,
    premium: false,
    name: 'jasonganub',
    total: 6,
    most_active_day: 'Wednesday',
    rank: 26,
    median: '1.20',
    missed_days: 26,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694079/commit_everyday_assets/link_l6rnaj.png',
    streak: 1,
  },
  {
    id: 73,
    premium: false,
    name: 'jcgoodwin86',
    total: 46,
    most_active_day: 'Monday',
    rank: 42,
    median: '3.29',
    missed_days: 20,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694084/commit_everyday_assets/superman_rdpvr2.png',
    streak: 5,
  },
  {
    id: 74,
    premium: false,
    name: 'jotolo',
    total: 190,
    most_active_day: 'Thursday',
    rank: 64,
    median: '9.50',
    missed_days: 11,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/naruto_uvarv7.png',
    streak: 12,
  },
  {
    id: 75,
    premium: false,
    name: 'Nix41',
    total: 126,
    most_active_day: 'Thursday',
    rank: 58,
    median: '5.04',
    missed_days: 9,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694083/commit_everyday_assets/spider_man_l5hdb4.png',
    streak: 6,
  },
  {
    id: 76,
    premium: false,
    name: 'Mmm',
    total: 49,
    most_active_day: 'Friday',
    rank: 42,
    median: '6.13',
    missed_days: 24,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694082/commit_everyday_assets/sonic_hbxuu3.png',
    streak: 2,
  },
  {
    id: 77,
    premium: false,
    name: 'Kar',
    total: 163,
    most_active_day: 'Wednesday',
    rank: 60,
    median: '10.87',
    missed_days: 16,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/princess_peach_zmfaz1.png',
    streak: 6,
  },
  {
    id: 78,
    premium: false,
    name: 'Kha',
    total: 54,
    most_active_day: 'Wednesday',
    rank: 44,
    median: '3.00',
    missed_days: 14,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/bullet_bill_vblqii.png',
    streak: 4,
  },
  {
    id: 79,
    premium: false,
    name: 'azan-n',
    total: 177,
    most_active_day: 'Saturday',
    rank: 70,
    median: '7.08',
    missed_days: 10,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/cloud_strife_oquw2g.png',
    streak: 7,
  },
  {
    id: 80,
    premium: false,
    name: 'scare-destiny',
    total: 84,
    most_active_day: 'Tuesday',
    rank: 52,
    median: '4.42',
    missed_days: 17,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694083/commit_everyday_assets/subzero_grsqdz.png',
    streak: 5,
  },
  {
    id: 81,
    premium: false,
    name: 'mateusz-skiba',
    total: 3,
    most_active_day: 'Thursday',
    rank: 24,
    median: '1.50',
    missed_days: 29,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/New_Project_p3lcxu.png',
    streak: 1,
  },
  {
    id: 82,
    premium: false,
    name: 'AvaterClasher',
    total: 134,
    most_active_day: 'Saturday',
    rank: 70,
    median: '4.79',
    missed_days: 7,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694079/commit_everyday_assets/master_chief_u7bven.png',
    streak: 11,
  },
  {
    id: 83,
    premium: false,
    name: 'chriswatterston',
    total: 161,
    most_active_day: 'Tuesday',
    rank: 58,
    median: '5.55',
    missed_days: 9,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/cloud_strife_oquw2g.png',
    streak: 6,
  },
  {
    id: 84,
    premium: false,
    name: 'odilsoncode',
    total: 192,
    most_active_day: 'Sunday',
    rank: 86,
    median: '5.05',
    missed_days: 0,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694077/commit_everyday_assets/iron_man_sms4o2.png',
    streak: 38,
  },
  {
    id: 85,
    premium: false,
    name: 'Blackie360',
    total: 160,
    most_active_day: 'Sunday',
    rank: 86,
    median: '4.10',
    missed_days: 0,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/cloud_strife_oquw2g.png',
    streak: 39,
  },
  {
    id: 86,
    premium: false,
    name: 'Antimonycodes',
    total: 50,
    most_active_day: 'Wednesday',
    rank: 44,
    median: '3.33',
    missed_days: 18,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694083/commit_everyday_assets/spider_man_l5hdb4.png',
    streak: 7,
  },
  {
    id: 87,
    premium: false,
    name: 'Ayendisimeon1',
    total: 138,
    most_active_day: 'Thursday',
    rank: 74,
    median: '3.63',
    missed_days: 0,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/crash_bandicoot_r5oa4m.png',
    streak: 35,
  },
  {
    id: 88,
    premium: false,
    name: 'sandepten',
    total: 359,
    most_active_day: 'Monday',
    rank: 70,
    median: '9.97',
    missed_days: 2,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694079/commit_everyday_assets/link_l6rnaj.png',
    streak: 16,
  },
  {
    id: 89,
    premium: false,
    name: 'Akshola00',
    total: 74,
    most_active_day: 'Tuesday',
    rank: 62,
    median: '2.11',
    missed_days: 5,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/pikachu_kmz3pu.png',
    streak: 23,
  },
  {
    id: 90,
    premium: false,
    name: 'DarshanBanait',
    total: 20,
    most_active_day: 'Saturday',
    rank: 40,
    median: '2.86',
    missed_days: 27,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/bullet_bill_vblqii.png',
    streak: 2,
  },
  {
    id: 91,
    premium: false,
    name: 'kalejaiyeoluwadara',
    total: 297,
    most_active_day: 'Friday',
    rank: 78,
    median: '7.07',
    missed_days: 0,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694076/commit_everyday_assets/gordon_freeman_awbqu9.png',
    streak: 42,
  },
  {
    id: 92,
    premium: false,
    name: 'mxpppe',
    total: 430,
    most_active_day: 'Tuesday',
    rank: 74,
    median: '11.32',
    missed_days: 3,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694084/commit_everyday_assets/superman_rdpvr2.png',
    streak: 19,
  },
  {
    id: 93,
    premium: false,
    name: 'Sammyfrosh35',
    total: 35,
    most_active_day: 'Tuesday',
    rank: 38,
    median: '1.75',
    missed_days: 24,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694083/commit_everyday_assets/spider_man_l5hdb4.png',
    streak: 7,
  },
  {
    id: 94,
    premium: false,
    name: 'eai04191',
    total: 89,
    most_active_day: 'Sunday',
    rank: 64,
    median: '4.05',
    missed_days: 17,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/batman_s79wx5.png',
    streak: 6,
  },
  {
    id: 95,
    premium: false,
    name: 'ize-302',
    total: 78,
    most_active_day: 'Friday',
    rank: 50,
    median: '3.25',
    missed_days: 17,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694085/commit_everyday_assets/yoshi_egg_vdpzao.png',
    streak: 5,
  },
  {
    id: 96,
    premium: false,
    name: 'kenbrittain',
    total: 269,
    most_active_day: 'Saturday',
    rank: 84,
    median: '4.89',
    missed_days: 5,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694078/commit_everyday_assets/knuckles_uu8knq.png',
    streak: 53,
  },
  {
    id: 97,
    premium: false,
    name: 'xyhtac',
    total: 1442,
    most_active_day: 'Monday',
    rank: 70,
    median: '51.50',
    missed_days: 14,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694084/commit_everyday_assets/wolverine_ccnnhd.png',
    streak: 7,
  },
  {
    id: 98,
    premium: false,
    name: 'IguJl15',
    total: 222,
    most_active_day: 'Thursday',
    rank: 60,
    median: '4.83',
    missed_days: 11,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694076/commit_everyday_assets/gordon_freeman_awbqu9.png',
    streak: 12,
  },
  {
    id: 99,
    premium: false,
    name: 'cybrarist',
    total: 53,
    most_active_day: 'Tuesday',
    rank: 42,
    median: '2.41',
    missed_days: 24,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694081/commit_everyday_assets/ryu_t29dkb.png',
    streak: 7,
  },
  {
    id: 100,
    premium: false,
    name: 'Susannakay',
    total: 30,
    most_active_day: 'Tuesday',
    rank: 32,
    median: '3.00',
    missed_days: 28,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/charizard_srtut3.png',
    streak: 2,
  },
  {
    id: 101,
    premium: false,
    name: 'ringoapple-sukebasuke',
    total: 843,
    most_active_day: 'Tuesday',
    rank: 72,
    median: '16.53',
    missed_days: 11,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694080/commit_everyday_assets/naruto_uvarv7.png',
    streak: 12,
  },
  {
    id: 102,
    premium: false,
    name: 'hekailiu-2512',
    total: 6535,
    most_active_day: 'Saturday',
    rank: 100,
    median: '85.99',
    missed_days: 0,
    image:
      'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694075/commit_everyday_assets/cloud_strife_oquw2g.png',
    streak: 76,
  },
  {
    id: 103,
    premium: false,
    name: 'joshmanders',
    total: 474,
    most_active_day: 'Wednesday',
    rank: 76,
    median: '5.93',
    missed_days: 0,
    image: 'https://res.cloudinary.com/dvz9avi1t/image/upload/v1706694076/commit_everyday_assets/kamek_lyavef.png',
    streak: 80,
  },
];
